### ISSUE TITLE
Allow us to use `{{version}}` in the custom join message.

### ISSUE THREAD

**Issue by byteveil** [lewmilburn/Essence#35]
My server currently has these welcome message:

```yml
motd:
  enabled: true
  message: |-
    §f[§aEssence§f] §7Hey, thank you for joining!
      §7We're using Essense 1.3.1.
      §7Use §c/help essence §7to see what's available.
```

I'd like to replace `1.3.1` with `{{version}}`, or something of that matter, so each time I make an update I do not have to open the configuration file to make that change.
